### ISSUE TITLE
IndexError: list index out of range in annotate_alphabets.py

### ISSUE THREAD

**Issue by byee4** [kaitlin309/PRIESSTESS#3]
Hi,

I'm trying to follow the documentation to re-process some test data, however I'm hitting an error:

```
gunzip /opt/PRIESSTESS/benchmarking_dataset/train_and_test_sets/TGGACT40NAATEMJ_*.gz
cat TGGACT40NAATEMJ_positive_trainset.txt TGGACT40NAATEMJ_positive_testset.txt > TGGACT40NAATEMJ_positive_set.txt
cat TGGACT40NAATEMJ_negative_trainset.txt TGGACT40NAATEMJ_negative_testset.txt > TGGACT40NAATEMJ_negative_set.txt
PRIESSTESS -fg TGGACT40NAATEMJ_positive_set.txt -bg TGGACT40NAATEMJ_negative_set.txt -flanksIn -f5 47 -f3 58 -t 37
Folding 22833 fg probes
22833 probes of 22833 have been folded
Traceback (most recent call last):
  File "/opt/PRIESSTESS/bin/annotate_alphabets.py", line 68, in <module>
    struct_7 = l.strip().split('\t')[2]
IndexError: list index out of range
Folding 22833 bg probes
22833 probes of 22833 have been folded
Traceback (most recent call last):
  File "/opt/PRIESSTESS/bin/annotate_alphabets.py", line 68, in <module>
    struct_7 = l.strip().split('\t')[2]
IndexError: list index out of range
Identifying motifs with alphabet seq-4
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the positive sequence file 'fg_STREME.fa'.
...
```

Any idea what is happening here? Thank you in advance!

**Comment by kaitlin309** [comment]
Hi!

Thank you for bringing this to my attention. I looked into it and it turns out that somehow the files ended up with Windows carriage returns:

```
(myenv) klaverty@nia-login07:~/github/PRIESSTESS/benchmarking_dataset/train_and_test_sets$ cat -A TGGACT40NAATEMJ_negative_set.txt | head
GGGAUAUCCUCCACGGAGUCGGCAAGCAGAAGACGGCAUACGAUUAACUUAAGCUUGGCAAGAGCACGAGACUGAGCAUCAGAGUUUAGUCCAAGAUCGGAAGAGCGUCGUGUAGGGAAAGAGUGUUCGGUGGUCGCCGUAUCAU^M$
GGGAUAUCCUCCACGGAGUCGGCAAGCAGAAGACGGCAUACGAUUAAAUAAGCGACGUCGCCUGGGUCAACGACGCGGAUUGAAGUCAGUCCAAGAUCGGAAGAGCGUCGUGUAGGGAAAGAGUGUUCGGUGGUCGCCGUAUCAU^M$
```

When the python file `annotate_alphabets.py` tries to read the file it ends up splitting up the lines. I have added some lines to the `PRIESSTESS` file to remove Windows carriage returns from the input files. If you want to just do it yourself, for each of your input files run:

`sed -i 's/\r//g' file_name.txt`

(or possibly `sed -e` depending on your OS)
